#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Builds the dataset and puts them into public/data
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        mkdir -p build-cache
        mkdir -p data/config

        # Copy config and data files
        cp "${DIR}/../../../data/processed/ihme-config.json" data/
        cp "${DIR}/../../../data/processed/ihme-country-data.json" data/
        cp "${DIR}/../../../data/processed/ihme-region-data.json" data/

        # Copy GeoJSON files
        cp "${DIR}/../../../data/processed/ihme-country.geojson" build-cache/
        cp "${DIR}/../../../data/processed/ihme-region.geojson" build-cache/

        # Replace all instances of NaN with null
        sed -i.bak 's/NaN/null/g' build-cache/*.geojson

        # Generate intermediate data set
        tippecanoe -f -pk -pf --no-tile-compression \
                   --maximum-zoom=8 --minimum-zoom=0 \
                   -e data/tiles \
                   --named-layer=country:build-cache/ihme-country.geojson \
                   --named-layer=region:build-cache/ihme-region.geojson

        # Synchronize everything to the Jekyll root
        rm -r public/data
        mv data public/data

    fi
fi
