#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build the site!
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        . "/usr/local/bin/run-build-functions.sh"

        mkdir -p build-cache
        mkdir -p data

        # Copy config file
        cp "${DIR}/../../../data/processed/ihme-config.json" data/

        # Copy GeoJSON files
        cp "${DIR}/../../../data/processed/ihme-country-data.geojson" build-cache/
        cp "${DIR}/../../../data/processed/ihme-region-data.geojson" build-cache/

        # Replace all instances of NaN with null
        sed -i.bak 's/NaN/null/' build-cache/*.geojson

        # Generate intermediate data set
        tippecanoe -f -pk -pf --no-tile-compression \
                   --maximum-zoom=8 --minimum-zoom=0 \
                   -e data/tiles \
                   --named-layer=country:build-cache/ihme-country-data.geojson \
                   --named-layer=region:build-cache/ihme-region-data.geojson

        # Build React application
        npm install
        # Set CI="" to avoid failing on warnings.
        CI="" npm run build

        # Synchronize everything to the Jekyll root
        rsync -avz \
            "${DIR}/../build/" "${DIR}/../../../_site/maps/ihme-explorer"
        rsync -avz \
            "${DIR}/../data/" "${DIR}/../../../_site/maps/ihme-explorer/data"
    fi
fi
