#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build the site!
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        npm install
        # Set CI="" to avoid failing on warnings.
        CI="" npm run build

        # Synchronize everything to the Jekyll root
        rsync -avz \
            "${DIR}/../build/" "${DIR}/../../../_site/maps/hghi-vents/"
    fi
fi
