#!/bin/bash

set -e

function usage() {

    echo -n \
"Usage: $(basename "$0")
Setup project containers.
"
}

function build_containers() {
    echo "Building containers"
    docker build -t covid19 -f docker/Dockerfile .
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        build_containers
    fi
    exit
fi
