#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
PROJECT_ROOT="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"

DATA_DIR="${COVID19_DATA_DIR:-${PROJECT_ROOT}/data}"
NOTEBOOK_DIR="${COVID19_NOTEBOOK_DIR:-${PROJECT_ROOT}/nbs}"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Launch Bash within the Jupyter container image.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it \
        -v "$PROJECT_ROOT":/opt/src \
        -v "$DATA_DIR":/opt/jupyter/data \
        -v "$NOTEBOOK_DIR":/opt/jupyter/nbs \
        --entrypoint /bin/bash \
        covid19:latest
fi
