#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
PROJECT_ROOT="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"

DATA_DIR="${COVID19_DATA_DIR:-${PROJECT_ROOT}/data}"
NOTEBOOK_DIR="${COVID19_NOTEBOOK_DIR:-${PROJECT_ROOT}/nbs}"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Generates the static site maps at covidcrisismap.org/maps

Options:
--hscap Only build the US Healthcare System Capacity map
"
}

HGHI_VENTS_CMD=$(cat <<-END
      mkdir -p maps && \
      cd viz/hghi-vents && \
      npx npm-force-resolutions && \
      npm install && npm run build && \
      rm -r ../../maps/hghi-vents && \
      cp -r build ../../maps/hghi-vents
END
)

HSCAP_CMD=$(cat <<-END
      mkdir -p maps && \
      cd viz/us-healthcare-system-capacity && \
      rm -r ../../maps/us-healthcare-system-capacity && \
      cp -r . ../../maps/us-healthcare-system-capacity && \
      rm -r ../../maps/us-healthcare-system-capacity/data/input
END
)

POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --help)
        usage
        exit 0
        shift
        ;;
        --hscap)
        HSCAP_ONLY=1
        shift # past argument
        ;;
    esac
done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ -z "${HSCAP_ONLY}" ]
    then
        ECHO "Building hghi-vents site..."
        docker run --rm -it \
               -v "$PROJECT_ROOT":/opt/src \
               --workdir /opt/src \
               --entrypoint /bin/bash \
               covid19:latest -c "$HGHI_VENTS_CMD"
    fi

    ECHO "Building us-healthcare-system-capacity site..."
    docker run --rm -it \
        -v "$PROJECT_ROOT":/opt/src \
        --workdir /opt/src \
        --entrypoint /bin/bash \
        covid19:latest -c "$HSCAP_CMD"
fi
