#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
PROJECT_ROOT="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"

DATA_DIR="${COVID19_DATA_DIR:-${PROJECT_ROOT}/data}"
NOTEBOOK_DIR="${COVID19_NOTEBOOK_DIR:-${PROJECT_ROOT}/nbs}"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Generates the static site maps at covidcrisismap.org/maps
"
}

HGHI_VENTS_CMD=$(cat <<-END
      mkdir -p maps && \
      cd viz/hghi-vents && \
      npx npm-force-resolutions && \
      npm install && npm run build && \
      cp -r build ../../maps/hghi-vents
END
)

HSCAP_CMD=$(cat <<-END
      mkdir -p maps && \
      cd viz/us-healthcare-system-capacity && \
      rm -r ../../maps/us-healthcare-system-capacity && \
      cp -r . ../../maps/us-healthcare-system-capacity && \
      rm -r ../../maps/us-healthcare-system-capacity/data/input
END
)


if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
   ECHO "Building hghi-vents site..."
    docker run --rm -it \
        -v "$PROJECT_ROOT":/opt/src \
        --workdir /opt/src \
        --entrypoint /bin/bash \
        covid19:latest -c "$HGHI_VENTS_CMD"

   ECHO "Building us-healthcare-system-capacity site..."
    docker run --rm -it \
        -v "$PROJECT_ROOT":/opt/src \
        --workdir /opt/src \
        --entrypoint /bin/bash \
        covid19:latest -c "$HSCAP_CMD"
fi
