#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi


SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
PROJECT_ROOT="$( cd -P "$( dirname "$SCRIPTS_DIR" )" && pwd )"

DATA_DIR="${COVID19_DATA_DIR:-${PROJECT_ROOT}/data}"
NOTEBOOK_DIR="${COVID19_NOTEBOOK_DIR:-${PROJECT_ROOT}/nbs}"

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run the jupyter notebook in a covid19 docker image locally
"
}

JUPYTER="-v ${NOTEBOOK_DIR}:/opt/jupyter -p 8888:8888"
CMD=(jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root --notebook-dir=/opt/jupyter)


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    docker run --rm -it \
           -e "AWS_PROFILE=$AWS_PROFILE" \
           -v "$HOME/.aws":/root/.aws:ro \
           -v "$PROJECT_ROOT":/opt/src \
           -v ${DATA_DIR}:/opt/jupyter/data \
           -v ${NOTEBOOK_DIR}:/opt/jupyter/nbs \
           --ip 0.0.0.0 \
           -p 8888:8888 \
           covid19:latest \
           "${CMD[@]}"
fi
