#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

IMAGE_NAME=covid19

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
PROJECT_ROOT="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"

DATA_DIR="${COVID19_DATA_DIR:-${PROJECT_ROOT}/data}"
NOTEBOOK_DIR="${COVID19_NOTEBOOK_DIR:-${PROJECT_ROOT}/notebooks}"


function usage() {
    echo -n \
        "Usage: $(basename "$0")
Proceess and update data that pulls from live sources.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it \
           -v "$PROJECT_ROOT":/opt/src \
           -v "$DATA_DIR":/opt/jupyter/data \
           -v "$NOTEBOOK_DIR":/opt/jupyter/notebooks \
           --entrypoint /opt/process-hscap-data \
           ${IMAGE_NAME}:latest
fi
