#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

IMAGE_NAME=covid19

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
PROJECT_ROOT="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"

DATA_DIR="${COVID19_DATA_DIR:-${PROJECT_ROOT}/data}"
NOTEBOOK_DIR="${COVID19_NOTEBOOK_DIR:-${PROJECT_ROOT}/notebooks}"


function usage() {
    echo -n \
        "Usage: $(basename "$0") DATASET
Proceess and update data that pulls from live sources.

Arguments:
        DATASET - Leave blank to run all data updates. HSCAP to run hscap notebooks. IHME to ruh ihme notebooks.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it \
           -v "$PROJECT_ROOT":/opt/src \
           -v "$DATA_DIR":/opt/jupyter/data \
           -v "$NOTEBOOK_DIR":/opt/jupyter/notebooks \
           -e AIRTABLE_KEY=${CCM_AIRTABLE_KEY} \
           ${IMAGE_NAME}:latest \
           $1
fi
