#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Generate the site!
"
}

NETLIFY_CACHE_DIR="/opt/buildhome/cache"

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

        mkdir -p ./build-cache/
        mkdir -p ${NETLIFY_CACHE_DIR}

        bundle config set path "$NETLIFY_CACHE_DIR/bundle"
        jekyll build

        # Install tippecanoe
        if [ ! -d $NETLIFY_CACHE_DIR/tippecanoe-1.32.5 ]; then
            wget -qO- https://github.com/mapbox/tippecanoe/archive/1.32.5.tar.gz |
                tar xvz -C build-cache/
            make -C build-cache/tippecanoe-1.32.5
            cp -R build-cache/tippecanoe-1.32.5 $NETLIFY_CACHE_DIR/tippecanoe-1.32.5
        fi

        export PATH=$NETLIFY_CACHE_DIR/tippecanoe-1.32.5:$PATH

        mkdir -p "${DIR}/../_site/maps"

        for map in "${DIR}"/../maps/*; do
            pushd "$map"

            if [ -f "./scripts/cibuild" ]; then
                source ./scripts/cibuild
            fi

            popd
        done
    fi
fi
