#!/bin/bash

set -e

if [[ -n "${COVID19_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Process data for CovidCareMap.
"
}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"

DATASET=${1}
UPDATE_ROOT=${2}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    if [ "${DATASET}" = "HSCAP" ]; then
        echo "RUNNING ONLY HSCAP"
        ${SCRIPT_DIR}/process-hscap-data ${UPDATE_ROOT}
    elif [ "${DATASET}" = "IHME" ]; then
        echo "RUNNING ONLY IHME"
        ${SCRIPT_DIR}/process-ihme-data ${UPDATE_ROOT}
    else
        echo "RUNNING ALL"
        ${SCRIPT_DIR}/process-hscap-data ${UPDATE_ROOT}
        ${SCRIPT_DIR}/process-ihme-data ${UPDATE_ROOT}
    fi
fi
